export const iconTable = {

  // Special
  'ANNOUNCEMENTS': 'fa-bullhorn',
  'MICSPAM': 'fa-headset',

  // Countries & Intl. Regions
  'AFRICA': 'fa-earth-africa',
  'AUS': 'fa-earth-oceania',
  'BALKAN': 'fa-earth-europe',
  'BENE': 'fa-earth-europe',
  'CAN': 'fa-earth-americas',
  'CANUCKS': 'fa-earth-americas',
  'CN-TW': 'fa-earth-asia',
  'CZECH': 'fa-earth-europe',
  'DEN': 'fa-earth-europe',
  'EUROPE': 'fa-earth-europe',
  'FIN': 'fa-earth-europe',
  'FRANCE': 'fa-earth-europe',
  'GER': 'fa-earth-europe',
  'IND': 'fa-earth-asia',
  'ISRAEL': 'fa-earth-africa',
  'IRELAND': 'fa-earth-europe',
  'ITALY': 'fa-earth-italy',
  'JAPAN': 'fa-earth-asia',
  'KOREA': 'fa-earth-asia',
  'LATAM': 'fa-earth-americas',
  'MAMADAS': 'fa-earth-americas',
  'MIDDLEEAST': 'fa-earth-africa',
  'NOR': 'fa-earth-europe',
  'NZ': 'fa-earth-oceania',
  'POLAND': 'fa-earth-europe',
  'RUS': 'fa-earth-europe',
  'SCAN': 'fa-earth-europe',
  'SEA': 'fa-earth-asia',
  'SWE': 'fa-earth-europe',
  'SWISS': 'fa-earth-europe',
  'UK': 'fa-earth-europe',
  'UKRAINE': 'fa-earth-europe',
  'V4': 'fa-earth-europe',
  'VODKA': 'fa-earth-europe',
  'WHATSAPP-FORWARDS': 'fa-earth-asia',
  'YUROP': 'fa-earth-europe',
  'LONDON': 'fa-city',
  'AUS-SYD': 'fa-city',
  'UCHICAGO': 'fa-graduation-cap',
  'UIUC': 'fa-graduation-cap',

  // US States, Cities & Regions
  'BAY-AREA':	'fa-city',
  'USA-ATL': 'fa-city',
  'USA-AZ': 'fa-flag-usa',
  'USA-CA': 'fa-flag-usa',
  'USA-CO': 'fa-flag-usa',
  'USA-CHI': 'fa-city',
  'USA-CVILLE':	'fa-city',
  'USA-DMV': 'fa-city',
  'USA-FL': 'fa-flag-usa',
  'USA-GA': 'fa-flag-usa',
  'USA-IN': 'fa-flag-usa',
  'USA-KC': 'fa-city',
  'LA': 'fa-city',
  'USA-MI': 'fa-flag-usa',
  'USA-MN': 'fa-flag-usa',
  'USA-MO': 'fa-flag-usa',
  'USA-MT': 'fa-flag-usa',
  'USA-NE': 'fa-flag-usa',
  'USA-NC': 'fa-flag-usa',
  'USA-NJ':	'fa-flag-usa',
  'USA-NY': 'fa-flag-usa',
  'USA-NYC': 'fa-city',
  'USA-OH': 'fa-flag-usa',
  'USA-OR': 'fa-flag-usa',
  'USA-PA': 'fa-flag-usa',
  'USA-SDG': 'fa-flag-usa',
  'USA-TX': 'fa-flag-usa',
  'USA-UT': 'fa-flag-usa',
  'USA-VA': 'fa-flag-usa',
  'USA-WA': 'fa-flag-usa',
  'USA-WI': 'fa-flag-usa',

  // Politicians
  'BIDEN': 'fa-democrat',
  'BUTTI': 'fa-democrat',	
  'COP': 'fa-democrat',
  'DELANEY': 'fa-democrat',
  'DIAMOND-JOE': 'fa-democrat',
  'GIGASUCC': 'fa-democrat',
  'OBAMA': 'fa-democrat',
  'OSBORNE': 'fa-check-to-slot',
  'PATERNALIST': 'fa-democrat',
  'QUACK': 'fa-democrat',
  'QUEEN': 'fa-democrat',
  'RICE': 'fa-democrat',
  'SALAD-COMB': 'fa-democrat',
  'SAUCER': 'fa-landmark-dome',
  'WELD': 'fa-republican',
  'YANG': 'fa-democrat',

  // Policy & Ideology
  'ALTRUISM': 'fa-handshake-simple',
  'BLUE-DOGS': 'fa-democrat',
  'CANLIB': 'fa-canadian-maple-leaf',
  'CUBE': 'fa-city',
  'DOWNBALLOT': 'fa-check-to-slot',
  'DEMOCRACY': 'fa-globe',
  'DEMS': 'fa-democrat',
  'ECO': 'fa-seedling',
  'ED-POLICY': 'fa-school-flag',
  'ELECTIONS': 'fa-check-to-slot',
  'FEMINISTS': 'fa-venus',
  'FOREIGN-POLICY': 'fa-dove',
  'GEORGIST': 'fa-globe',
  'HEALTH-POLICY': 'fa-staff-aesculapius',
  'IMMIGRATION': 'fa-passport',
  'INTERNATIONAL-RELATIONS': 'fa-globe',
  'LABOR': 'fa-hand-holding-dollar',
  'LAW': 'fa-scale-balanced',
  'LDC': 'fa-globe',
  'MARKETS':	'fa-arrow-trend-up',
  'MILITARY': 'fa-jet-fighter',
  'OSINT': 'fa-eye',
  'PIDGIN': 'fa-landmark-dome',
  'RADXC': 'fa-handshake-simple',
  'RINO': 'fa-republican',
  'SNEK': 'fa-worm',
  'TAX': 'fa-sack-dollar',
  'TRANSHUMANISM': 'fa-microchip',
  'TRANSIT': 'fa-train-subway',
  'YIMBY': 'fa-city',

  // Sports
  'BASEBALL': 'fa-baseball',
  'CBB': 'fa-basketball',
  'CFB': 'fa-football',
  'CRICKET': 'fa-baseball-bat-ball',
  'FFB': 'fa-football',
  'MMA': 'fa-person-running',
  'MOTO': 'fa-flag-checkered',
  'OLYMPICS': 'fa-person-running',
  'PRO-WRESTLING': 'fa-person-running',
  'NBA': 'fa-basketball',
  'NFL': 'fa-football',
  'NHL': 'fa-hockey-puck',
  'SOCCER': 'fa-futbol',
  'TENNIS': 'fa-baseball',

  // Music
  'CLASSICAL': 'fa-music',
  'ELECTRONICA': 'fa-music',
  'FASH-TUNES': 'fa-music',
  'FOLK': 'fa-music',
  'INDIE': 'fa-music',
  'JAZZ': 'fa-music',
  'METAL': 'fa-music',
  'MUSICIAN': 'fa-music',
  'OONTS': 'fa-music',
  'POP': 'fa-music',
  'PRETENTIOUS': 'fa-music',
  'PUNK': 'fa-music',
  'RAP': 'fa-music',
  'ROCK': 'fa-music',
  'WORLD-MUSIC': 'fa-music',

  // TV / Movies / Video / Books

  // Games
  'GAMING': 'fa-gamepad',

  // Demographics & Religion
  'ALPHABET-MAFIA': 'fa-rainbow',

  // Interests & Fun
  'DOG': 'fa-dog',
  'DYEL': 'fa-dumbbell',
  'FURRY': 'fa-paw',
  'PHOTO': 'fa-camera',
  'TRAVEL': 'fa-map-location-dot',

  // Health & Wellness
  'FITNESS': 'fa-person-running',
};