function getItems() {
    const items = {
        'special': ['ANNOUNCEMENTS', 'MICSPAM'],

        'itl': ['AFRICA', 'AUS', 'AUS-SYD', 'BALKAN', 'BENE', 'CAN', 'CANUCKS', 'CN-TW', 'CZECH', 'DEN', 'EUROPE', 'FIN', 'FRANCE', 'GER', 'IND', 'ISRAEL', 'IRELAND', 'ITALY', 'JAPAN', 'KOREA', 'LATAM', 'MAMADAS', 'MIDDLEEAST', 'NOR', 'NZ', 'POLAND', 'RUS', 'SCAN', 'SEA', 'SWE', 'SWISS', 'UK', 'LONDON', 'UKRAINE', 'V4', 'VODKA', 'WHATSAPP-FORWARDS', 'YUROP'],

        'usa': ['BAY-AREA', 'USA-ATL', 'USA-AZ', 'USA-CA', 'USA-CO', 'USA-CHI', 'USA-CVILLE', 'USA-DMV', 'USA-FL', 'USA-GA', 'USA-IN', 'USA-KC', 'LA', 'USA-MI', 'USA-MN', 'USA-MO', 'USA-MT', 'USA-NE', 'USA-NC', 'USA-NJ', 'USA-NY', 'USA-NYC', 'USA-OH', 'USA-OR', 'USA-PA', 'USA-SDG', 'USA-TX', 'USA-UT', 'USA-VA', 'USA-WA', 'USA-WI', 'UCHICAGO', 'UIUC'],

        'fun': ['ALCHOL', 'ALTHISTORY', 'ANDROID', 'AOC', 'AUTO', 'ARCHITECTURE', 'AWW', 'BAJA', 'COFFEE', 'CONSOLE-WARS', 'DOG', 'DYEL', 'FAKE-ROTHKO', 'FASHION', 'FAST-FOOD', 'FURRY', 'GOLF', 'GARAND', 'HONKHONK', 'KITTY', 'LINUX', 'MATERIEL', 'OUTDOORS', 'PANDA', 'PHOTO', 'PC-BUILDING', 'RELIGION', 'SCHIIT', 'SPACEFLIGHT', 'TECH', 'TRAVEL', 'TRIVIA', 'VR', 'WATERCOOLER', 'WEED', 'WHOREOLOGY', 'WRITING'],

        'academia': ['ACCOUNTING', 'AI', 'ASTRONOMY', 'AVIATION', 'BIGDATA', 'BIOLOGY', 'CAREER', 'COLLEGE', 'CLASSICS', 'COMPUTER-SCIENCE', 'CYBERSECURITY', 'COURT-CASE', 'DEBATE', 'ECE', 'ECON', 'HISTORY', 'LANGUAGE', 'LAW-SCHOOL', 'MATHEMATICS', 'MEDICINE', 'MUN', 'PHILOSOPHY', 'PHYSICS', 'POLIJOBS', 'SOCIAL-SCIENCE', 'STEM', 'TEACHERS', 'TRANSLATION']
    }
    return items;
}

export default getItems;